spring.application.name=FlightReservationApplication

spring.datasource.url=terraform-20260609104458374300000002.cv00iiwam8ez.us-east-2.rds.amazonaws.com:3306/flightdb?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Redhat123
frontend.url=http://3.93.154.213:80


# Hibernate properties for MySQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.auto-commit=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.address=0.0.0.0
